name: pre-merge-checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  initial_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check code using ruff
        uses: chartboost/ruff-action@v1

      - name: Check docstrings using interrogate
        run: |
          pip install interrogate
          if [ $(interrogate -c pyproject.toml -v . -f 100 | grep "FAILED" | wc -l) = 1 ]; then
             echo "necessary docstrings missing:"
             interrogate -vv . -f 100 
             exit 1
          fi

      - name: Check code formatting using black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "~= 22.6"

  standard_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
       

    needs: [initial_checks]
    steps:
      - uses: actions/checkout@v3      


      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: 'echo "$IDEAS_PAT" > .ideas-github-token'
        shell: bash
        env:
          IDEAS_PAT: ${{secrets.IDEAS_PAT}}

      - name: run unit tests
        run: |
          pip install -e .
          pip install pytest coverage 
          pip install git+https://${{ secrets.IDEAS_PAT }}@github.com/inscopix/ideas-data.git
          make test-pip



  

